version: '3.8'

services:
  frontend:
    build:
      context: ./lnt-frontend
      dockerfile: Dockerfile_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./lnt-backend
      dockerfile: Dockerfile_backend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
